### ISSUE TITLE
KTR_INFINITY not defined

### ISSUE THREAD

**Issue by PEPERSO** [JuliaSmoothOptimizers/NLPModelsKnitro.jl#12]
Hi, running NCL with NLPModelsKnitro, I get the following error :
```ERROR: LoadError: UndefVarError: KTR_INFINITY not defined```

Is there anything I could do to fix it ? I tried to set ```KTR_INFINITY``` to ```1e30``` before calling KNITRO, but it did not work...

**Comment by dpo** [comment]
What version of Knitro are you using?

**Comment by PEPERSO** [comment]
KNITRO 12.0.0 and KNITRO.jl 0.7.0

**Comment by dpo** [comment]
Are you using an old version of this package? We use `KN_INFINITY` (not `KTR_INFINITY`): https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/blob/master/src/NLPModelsKnitro.jl#L55

**Comment by PEPERSO** [comment]
No, sorry, I stopped working on NCL, so I didn't try to fix this.

**Comment by dpo** [comment]
I think it was due to an outdated version of either KNITRO or NLPModelsKnitro.
