### ISSUE TITLE
Cannot run basic example

### ISSUE THREAD

**Issue by PierreMartinon** [JuliaSmoothOptimizers/NLPModelsKnitro.jl#132]
Hi everyone,
When I try the first example
```
using ADNLPModels, NLPModelsKnitro

nlp = ADNLPModel(x -> (x[1] - 1)^2 + 100 * (x[2] - x[1]^2)^2, [-1.2; 1.0])
stats = knitro(nlp)
print(stats)
```
I get the following error
```
julia> stats = knitro(nlp)
ERROR: MethodError: no method matching knitro(::ADNLPModel{Float64, Vector{Float64}, Vector{Int64}})
The function `knitro` exists, but no method is defined for this combination of argument types.
```
It seems there are no methods defined
```
julia> knitro
knitro (generic function with 0 methods)
```

Any idea what I missed ?

**Comment by tmigot** [comment]
Hi @PierreMartinon ! That's strange. What happens if you do `using KNITRO`? Is there a warning?

**Comment by PierreMartinon** [comment]
Ok, I probably need to get the academic license and actually install knitro :D
With `add KNITRO` and `using KNITRO` I get what seems to be an empty package.

**Comment by tmigot** [comment]
@PierreMartinon When doing `] add NLPModelsKnitro` you should have had the following error:
![image](https://github.com/user-attachments/assets/ddc11d7e-5015-426e-a258-f4da27a0429d)
which warns you something is wrong.
