### ISSUE TITLE
Return cons, grad, hess evaluations at the solution

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModelsKnitro.jl#55]
The package KNITRO.jl offers the possibility to return the gradient, hessian, constraint, jacobian evaluations at the solution.
This is very useful, in particular, if KNITRO is used to solve a subproblem.

We probably don't want to return all these evaluations in the `GenericExecutionStats` to avoid allocating unnecessary memory. 
So, I see at least two options:
- we return as a `solver_specific` the KNITRO-model/object.
- we create a KNITROSolver structure with a KNITRO-model/object as an attribute.

@abelsiqueira @dpo Any suggestion?

I am using it in the [Fletcher's penalty solver](https://github.com/tmigot/FletcherPenaltyNLPSolver).

**Comment by dpo** [comment]
Could you add a link to the documentation describing how to retrieve those values?

**Comment by tmigot** [comment]
Here is the link to the documentation [Reading model/solution properties](https://www.artelys.com/docs/knitro//3_referenceManual/callableLibraryAPI.html#reading-model-solution-properties)

There is no further doc for KNITRO.jl, but the useful functions can be found in [src/kn_attributes.jl](https://github.com/jump-dev/KNITRO.jl/blob/2cf693009476cbaebcec5137140b807a8d613b0f/src/kn_attributes.jl#L79).

**Comment by dpo** [comment]
Could we return the `kc` object in `stats` so the user can query those if they want? I don’t think we should store entire Hessians or Jacobians in `stats`...

**Comment by tmigot** [comment]
Agreed. I think we can pass the `kc` object, the only drawback is that the user has to use `KNITRO.KN_free(kc)` (which is done right now at the end of the `knitro` call) to "finalize" the model similar to a CUTEstModel.

Another alternative would use kwargs so that the user asks from the solver call for the returned values.

**Comment by dpo** [comment]
Yes, that’s better. Let’s make it optional. But does that mean we need a KnitroSolver to preallocate?

**Comment by tmigot** [comment]
Yes, a KnitroSolver would be a clean way to do it. So, the user needs to specify the evals from the initialization of the KnitroSolver.

**Comment by dpo** [comment]
Yes. There could be a check in the solver that the space has been allocated (and an error if it hasn’t).

**Comment by dpo** [comment]
If we have a KnitroSolver, then we could store `kc` in it, and write a finalizer. That would allow users to perform solves of the same problem from a different starting point, etc.

**Comment by tmigot** [comment]
> If we have a KnitroSolver, then we could store `kc` in it, and write a finalizer. That would allow users to perform solves of the same problem from a different starting point, etc.

Great, I will make it concrete in a PR.
